### ISSUE TITLE
SSL Protocol

### ISSUE THREAD

**Issue by angrytec** [appmattus/certificatetransparency#104]
In LogListDataSourceFactory, is there a reason why SSL is specifically used here and not TLS ?

sslContext = SSLContext.getInstance("SSL")

**Comment by anamarin09041995** [comment]
Wondering the same since LogListDataSourceFactory class is marked by Veracode as insecure due to the use of the SSL protocol. The recommendation to remove this warning is to replace the protocol with TLS (TLS 1.2 preferred). Is there a  reason to maintain SSL?

**Comment by mattmook** [comment]
This is a very good question. I'm also not entirely sure why this hadn't been raised in any of the security scans the library has been in that I'd seen. 🤷 

While it may say SSL, SSLv3 support was dropped since Java SE 7u75 so it will usually be using TLS as a minimum anyway. That being said, the min Android SDK is API 19 (Android 4.4), and I'm not sure on its supported protocols.

It's worth noting that the log list data is signed with a public/private key pair so the risk comes down to man in the middle attack pushing stale data which the library protects itself against given that log-list.json the file contains a timestamp.

Given the library makes as few assertions of what platform it is running on I cannot easily enforce a precise protocol (or cipher suite), but will expose OkHttp's ConnectionSpec to allow this to be configured through `LogListDataSourceFactory.createLogListService`. The default is MODERN_TLS.
